#!/bin/bash

# Exit on first failing command.
set -e
# Echo commands to console.
set -x

IMAGE_NAME="firestore-emulator"
CONTAINER_NAME="firestore-emulator"
FIRESTORE_PROJECT_ID="dummy-project-id"

docker version

# Clear any previous container.
docker rm -f "$CONTAINER_NAME" || true

docker build \
  --tag "$IMAGE_NAME" \
  .

#docker run \
#  --name "$CONTAINER_NAME" \
#  --detach \
#  --env "FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}" \
#  --publish "8080:8080" \
#  --publish "8081:8081" \
#  -v data:/data \
#  "$IMAGE_NAME"

